/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alexscode_jnidemo_NativeWrapper */

#ifndef _Included_com_alexscode_jnidemo_NativeWrapper
#define _Included_com_alexscode_jnidemo_NativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alexscode_jnidemo_NativeWrapper
 * Method:    solve
 * Signature: (Lcom/alexscode/jnidemo/AnObject;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_alexscode_jnidemo_NativeWrapper_solve
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
